apiVersion: apps/v1
kind: Deployment
metadata:
  name: migrationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migrationservice
  template:
    metadata:
      labels:
        app: migrationservice
    spec:
      containers:
      - name: migrationservice
        image: cognixacr.azurecr.io/cognix/migrationservice:main
        envFrom:
        - configMapRef:
            name: cockroach-cli
        volumeMounts:
        - mountPath: /versions
          name: storage-volume             
      imagePullSecrets:
        - name: pullsecret
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: versions-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: versions-volume
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile-csi           