version: '3.8'  # Use Docker Compose file version 3.8

networks:
  cognix-network:
    driver: bridge
    name: cognix-network

services:
  cockroach:
    image: cockroachdb/cockroach:latest-v23.2
    ports:
      - "26257:26257"
      - "28080:8080"
    command: start-single-node --insecure
    volumes:
      - "../data/cockroach:/cockroach/cockroach-data"
    networks:
      - cognix-network
