version: '3.5'

services:
  api:
    image: cognix:api
    build:
      context: ${BACKEND_PATH}
      args:
        service: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ${CONFIG_PATH}/api_srv.env
      - ${CONFIG_PATH}/cockroach_cli.env
      - ${CONFIG_PATH}/minio_cli.env
      - ${CONFIG_PATH}/milvus_cli.env
      - ${CONFIG_PATH}/nats_cli.env
      - ${CONFIG_PATH}/embedder_cli.env
      - ${CONFIG_PATH}/.env
    volumes:
      - ${BACKEND_PATH}:/backend
    networks:
      - cognix-network

  orchestrator:
    image: cognix:orchestrator
    build:
      context: ${BACKEND_PATH}
      args:
        service: orchestrator
      dockerfile: Dockerfile
    env_file:
      - ${CONFIG_PATH}/orchestrator_srv.env
      - ${CONFIG_PATH}/cockroach_cli.env
      - ${CONFIG_PATH}/nats_cli.env
      - ${CONFIG_PATH}/.env
    volumes:
      - ${BACKEND_PATH}:/backend
    networks:
      - cognix-network

  connector:
    image: cognix:connector
    build:
      context: ${BACKEND_PATH}
      args:
        service: connector
      dockerfile: Dockerfile
    env_file:
      - ${CONFIG_PATH}/connector_srv.env
      - ${CONFIG_PATH}/cockroach_cli.env
      - ${CONFIG_PATH}/nats_cli.env
      - ${CONFIG_PATH}/milvus_cli.env
      - ${CONFIG_PATH}/minio_cli.env
      - ${CONFIG_PATH}/oauth_cli.env
      - ${CONFIG_PATH}/.env
    volumes:
      - ${BACKEND_PATH}:/backend
    networks:
      - cognix-network

  migration:
    image: cognix:migration
    build:
      context: ${MIGRATION_PATH}
      dockerfile: Dockerfile

    volumes:
      - ${MIGRATION_PATH}/versions:/versions
    env_file:
      - ${CONFIG_PATH}/cockroach_cli.env
    networks:
      - cognix-network

volumes:
  db_volume:
  nats-storage:

networks:
  cognix-network:
    # external: true
    name: cognix-network