version: '3.8'  # Use Docker Compose file version 3.8

networks:
  cognix-network:
    external:
      name: cognix-network

services:
  nats:
    image: nats:latest  # Use the latest NATS image
    container_name: nats
    ports:
      - "4222:4222"  # Client connections to NATS
      - "8222:8222"  # HTTP monitoring port for NATS
      - "6222:6222"  # Cluster port for NATS
    volumes:
      - nats-storage:/data/nats
    command:
      - "--name=nats"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data/nats"
    networks:
      - cognix-network
  nats-streaming-ui:
    build: .
    image: piotrpersona/nats-ui:latest
    ports:
      - "8282:8282"
    networks:
      - cognix-network

volumes:
  nats-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../data/nats
