# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embed_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65mbed_service.proto\x12\ncom.embedd\".\n\x0c\x45mbedRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\"\x1f\n\rEmbedResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x32T\n\x0c\x45mbedService\x12\x44\n\x0bGetEmbeding\x12\x18.com.embedd.EmbedRequest\x1a\x19.com.embedd.EmbedResponse\"\x00\x42\x1aZ\x18\x62\x61\x63kend/core/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embed_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030backend/core/proto;proto'
  _globals['_EMBEDREQUEST']._serialized_start=35
  _globals['_EMBEDREQUEST']._serialized_end=81
  _globals['_EMBEDRESPONSE']._serialized_start=83
  _globals['_EMBEDRESPONSE']._serialized_end=114
  _globals['_EMBEDSERVICE']._serialized_start=116
  _globals['_EMBEDSERVICE']._serialized_end=200
# @@protoc_insertion_point(module_scope)
