apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiservice
  template:
    metadata:
      labels:
        app: apiservice
    spec:
      containers:
      - name: apiservice
        image: cognixacr.azurecr.io/cognix/apiservice:main
        envFrom:
        - configMapRef:
            name: api-srv
        - configMapRef:
            name: cockroach-cli
        - configMapRef:
            name: minio-cli
        - configMapRef:
            name: milvus-cli
        - configMapRef:
            name: nats-cli
        - configMapRef:
            name: embedder-cli
        - configMapRef:
            name: env-configmap
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /backend
          name: storage-volume 
        imagePullPolicy: Always
      imagePullSecrets:
        - name: pullsecret
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: storage-volume
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: apiservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-volume
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile-csi